# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetial',
            new_name='CourseDetail',
        ),
    ]
