# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-05 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='enrolled_course',
        ),
        migrations.DeleteModel(
            name='CourseReview',
        ),
    ]
